#!/bin/sh
INDELIBLE_HOME=/usr/share/igeek/indelible-fs/lib
NATIVE_LIBS=/usr/lib/igeek/indelible-fs
CLASSPATH=""
for i in "$INDELIBLE_HOME"/*.jar
do
	CLASSPATH="$CLASSPATH:$i"
done
export CLASSPATH
/usr/bin/java -Djava.library.path="$NATIVE_LIBS" \
com.igeekinc.indelible.indeliblefs.utilities.IndelibleCopyInFile --fsid $1 --source $2 --create $3

